// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia.Context;

#nullable disable

namespace Persistencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dominio.Administrador.Actividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha anulación del registro");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PadreId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasComment("Id de la actividad padre de acuerdo con la jerarquia");

                    b.Property<string>("VcDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VcIcono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VcNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VcRedireccion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Actividad", (string)null);
                });

            modelBuilder.Entity("Dominio.Administrador.ActividadRol", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActividadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId", "ActividadId");

                    b.HasIndex("ActividadId");

                    b.ToTable("ActividadRol");
                });

            modelBuilder.Entity("Dominio.Administrador.Configuracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BDomingoLaboral")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<bool>("BSabadoLaboral")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IDiasLimiteRespuesta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Configuracion", (string)null);
                });

            modelBuilder.Entity("Dominio.Administrador.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaProrroga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaTerminacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IAño")
                        .HasColumnType("int");

                    b.Property<int>("INumero")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("Dominio.Administrador.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2")
                        .HasComment("Fecha Eliminacion del registro");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("VcDescripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VcIcono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VcNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VcRedireccion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Modulo", (string)null);
                });

            modelBuilder.Entity("Dominio.Administrador.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("VcCodigoInterno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VcNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Parametro", (string)null);
                });

            modelBuilder.Entity("Dominio.Administrador.ParametroDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DCodigoIterno")
                        .HasPrecision(17, 3)
                        .HasColumnType("decimal(17,3)");

                    b.Property<Guid>("ParametroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RangoDesde")
                        .HasColumnType("int");

                    b.Property<int?>("RangoHasta")
                        .HasColumnType("int");

                    b.Property<string>("TxDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcCodigoInterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VcNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParametroId");

                    b.ToTable("ParametroDetalle", (string)null);
                });

            modelBuilder.Entity("Dominio.Administrador.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VcCodigoInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Dominio.Administrador.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DtFechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcCorreo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcIdAzure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcPrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcPrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcSegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcSegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VcTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioArea", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParametroDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "ParametroDetalleId");

                    b.HasIndex("ParametroDetalleId");

                    b.ToTable("UsuarioArea");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioCargo", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParametroDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "ParametroDetalleId");

                    b.HasIndex("ParametroDetalleId");

                    b.ToTable("UsuarioCargo");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioPuntoAtencion", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParametroDetalleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DtFechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtFechaIncio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "ParametroDetalleId");

                    b.HasIndex("ParametroDetalleId");

                    b.ToTable("UsuarioPuntoAtencion");
                });

            modelBuilder.Entity("Dominio.Administrador.Actividad", b =>
                {
                    b.HasOne("Dominio.Administrador.Modulo", "Modulo")
                        .WithMany("Actividades")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Actividad_Modulo");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Dominio.Administrador.ActividadRol", b =>
                {
                    b.HasOne("Dominio.Administrador.Actividad", "Actividad")
                        .WithMany("ActividadRoles")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Administrador.Rol", "Rol")
                        .WithMany("ActividadRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Dominio.Administrador.Contrato", b =>
                {
                    b.HasOne("Dominio.Administrador.Usuario", "Usuario")
                        .WithMany("Contrato")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Administrador.ParametroDetalle", b =>
                {
                    b.HasOne("Dominio.Administrador.Parametro", "Parametro")
                        .WithMany("ParametroDetalles")
                        .HasForeignKey("ParametroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parametro");
                });

            modelBuilder.Entity("Dominio.Administrador.Rol", b =>
                {
                    b.HasOne("Dominio.Administrador.Modulo", "Modulo")
                        .WithMany("Roles")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioArea", b =>
                {
                    b.HasOne("Dominio.Administrador.ParametroDetalle", "ParametroDetalle")
                        .WithMany("UsuarioAreas")
                        .HasForeignKey("ParametroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Administrador.Usuario", "Usuario")
                        .WithMany("UsuarioAreas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametroDetalle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioCargo", b =>
                {
                    b.HasOne("Dominio.Administrador.ParametroDetalle", "ParametroDetalle")
                        .WithMany("UsuarioCargos")
                        .HasForeignKey("ParametroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Administrador.Usuario", "Usuario")
                        .WithMany("UsuarioCargos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametroDetalle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Administrador.UsuarioPuntoAtencion", b =>
                {
                    b.HasOne("Dominio.Administrador.ParametroDetalle", "ParametroDetalle")
                        .WithMany("UsuarioPuntoAtenciones")
                        .HasForeignKey("ParametroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Administrador.Usuario", "Usuario")
                        .WithMany("UsuarioPuntoAtenciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParametroDetalle");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Dominio.Administrador.Actividad", b =>
                {
                    b.Navigation("ActividadRoles");
                });

            modelBuilder.Entity("Dominio.Administrador.Modulo", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Dominio.Administrador.Parametro", b =>
                {
                    b.Navigation("ParametroDetalles");
                });

            modelBuilder.Entity("Dominio.Administrador.ParametroDetalle", b =>
                {
                    b.Navigation("UsuarioAreas");

                    b.Navigation("UsuarioCargos");

                    b.Navigation("UsuarioPuntoAtenciones");
                });

            modelBuilder.Entity("Dominio.Administrador.Rol", b =>
                {
                    b.Navigation("ActividadRoles");
                });

            modelBuilder.Entity("Dominio.Administrador.Usuario", b =>
                {
                    b.Navigation("Contrato");

                    b.Navigation("UsuarioAreas");

                    b.Navigation("UsuarioCargos");

                    b.Navigation("UsuarioPuntoAtenciones");
                });
#pragma warning restore 612, 618
        }
    }
}
